# Generated by Django 4.2.26 on 2025-11-24 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('api_id', models.IntegerField()),
                ('capa_url', models.URLField(blank=True, max_length=500, null=True)),
                ('nota_pessoal', models.IntegerField(default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
