# Generated by Django 4.2.26 on 2025-11-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('api_id', models.IntegerField(help_text='ID do filme no TMDB', unique=True)),
                ('capa_url', models.URLField(blank=True, max_length=500, null=True)),
                ('nota_pessoal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
